<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            '3T',
            'AddMotoR',
            'Aegis',
            'Airborne',
            'Airdrop',
            'Alchemy',
            'All City',
            'Allied',
            'Alutech',
            'Amego',
            'Ancheer',
            'Antidote',
            'Aquila',
            'Argon 18',
            'Ariel Rider',
            'Aventon',
            'B’TWIN',
            'Banshee',
            'BASIS',
            'Basso',
            'Batch Bicycles',
            'BATRI BIKE',
            'Bearclaw',
            'Benno',
            'Bergamont',
            'Berria',
            'BH',
            'Bianchi',
            'Biktrix',
            'Bird',
            'Blix',
            'Bluejay',
            'BMC',
            'Boardman',
            'Bombtrack',
            'BPM Imports',
            'Breezer',
            'Brodie',
            'Calibre',
            'California Bicycle Factory',
            'Canfield',
            'Cannondale',
            'Canyon',
            'Carrera',
            'Casati',
            'Cervélo',
            'Chromag',
            'Cinelli',
            'Cipollini',
            'CIVI BIKES',
            'Claud Butler',
            'Cleary',
            'Co-op',
            'Colnago',
            'Commençal',
            'Conway',
            'Corima',
            'Cotic',
            'CRUSSIS',
            'CTM',
            'CU',
            'BE',
            'CUDA',
            'Curve',
            'DALLINGRIDGE',
            'Dartmoor',
            'Dassi',
            'Dawes',
            'De Rosa',
            'Del Sol',
            'DENVER',
            'Devinci',
            'Diamondback',
            'DINO BIKES',
            'DMR',
            'DŌST',
            'e-Joe',
            'E-Lux',
            'Eahora',
            'Early Rider',
            'Early Rider Limited',
            'Eddy Merckx',
            'EG',
            'Electra',
            'Electric Bike Company',
            'Electric Bike Technologies',
            'Ellsworth',
            'ELOPS',
            'Eminent',
            'EMOJO',
            'EMU BIKES',
            'Enzo e Bikes',
            'Esker',
            'Espin',
            'EUNORAU',
            'EVELO',
            'Evil',
            'Falcon',
            'Faraday',
            'Felt',
            'Fezzari',
            'FLX',
            'Focus',
            'Foes',
            'Fondriest',
            'Forbidden',
            'Forestal',
            'Forme',
            'FTH Power',
            'Fuji',
            'Furo Systems',
            'Gazelle',
            'Genesis',
            'GeoMetron',
            'Gepida',
            'Ghost',
            'Giant',
            'GLOBBER',
            'Go Power',
            'Gocycle',
            'Growler Bikes',
            'GT',
            'Guerrilla Gravity',
            'Guru',
            'Haibike',
            'Haro',
            'Himiway',
            'Holdsworth',
            'Hope Technology',
            'HOY',
            'Husqvarna',
            'Ibis',
            'iGO Electric',
            'Intense',
            'IZIP',
            'Jamis',
            'Juiced Bikes',
            'Juliana',
            'Jupiter Bike',
            'K2',
            'Kellys',
            'Kestrel',
            'KHS',
            'Kinesis',
            'Knolly',
            'Kona',
            'Kross',
            'KTM',
            'Kuota',
            'Lapierre',
            'Lauf',
            'Lectric eBikes',
            'Liberty Trike',
            'Lightweight',
            'Litespeed',
            'Liteville',
            'Liv',
            'Lombardo',
            'Look',
            'Lynskey',
            'M2S',
            'Magnum',
            'Marin',
            'Masi',
            'MAXFOOT',
            'MDE',
            'Meek Boyz',
            'Megamo',
            'Merida',
            'Merlin',
            'MMR',
            'MOD BIKES',
            'Momentum',
            'Mondraker',
            'Mongoose',
            'Montague',
            'Moots',
            'Motiv',
            'Motobecane',
            'Moustache',
            'Nakto',
            'NCM',
            'Nicolai',
            'Niner',
            'Nireeka',
            'Norco',
            'NS',
            'Nukeproof',
            'O.P.E.N.',
            'Obed',
            'Ocoee',
            'OHM',
            'On-One',
            'Opus',
            'Orange',
            'Orbea',
            'Orro',
            'Otso',
            'Pace',
            'Parlee',
            'Pashley',
            'Patrol',
            'Pedego',
            'PEGASUS',
            'Pendleton',
            'Pinarello',
            'Pinnacle',
            'Pivot',
            'Planet X',
            'Pole',
            'Polygon',
            'Poseidon',
            'Prevelo',
            'Priority',
            'Privateer',
            'Production Privée',
            'Propain',
            'Propella',
            'Pure',
            'Pyga',
            'Qualisports',
            'Quintana Roo',
            'RAAW',
            'Rad Power Bikes',
            'Radon',
            'Ragley',
            'Raleigh',
            'Rambo Bikes',
            'Rattan',
            'Redline',
            'REEB',
            'Revel',
            'Revolve',
            'Ribble',
            'Ride1Up',
            'Ridley',
            'Riese & Müller',
            'Ritchey',
            'RIVERSIDE',
            'RIZE Bikes',
            'ROCKRIDER',
            'Rocky Mountain',
            'Rondo',
            'ROODOG',
            'Rose',
            'Rotwild',
            'RSD',
            'Sage',
            'Salsa',
            'Santa Cruz',
            'Saracen',
            'Savadeck',
            'SCAMP',
            'Schwinn',
            'SCOR',
            'Scott',
            'Sensa',
            'Serial 1',
            'Soma',
            'Sonder',
            'SONDORS',
            'Soul Fast E Bikes',
            'Spark Bikes',
            'Spawn',
            'Specialized',
            'Spot Brand',
            'Standert',
            'Stanton',
            'State Bicycle Co.',
            'Stevens',
            'STILUS',
            'Storck',
            'Strider',
            'Stromer',
            'Super73',
            'Superior',
            'Surface 604',
            'Surly',
            'Synergy',
            'Tern',
            'Thesis',
            'Time',
            'Titus',
            'Tommaso',
            'Tower',
            'Trailcraft',
            'Transition',
            'Trek',
            'Triban',
            'Turner',
            'Urban Arrow',
            'Urban Drivestyle',
            'Vaast',
            'Van Dessel',
            'VAN RYSEL',
            'Velec',
            'Verde',
            'Viathon',
            'Viking',
            'Vintage Electric',
            'Vitus',
            'Volt Bike',
            'Voodoo',
            'Whyte',
            'Wiggins',
            'Wildsyde',
            'Wilier',
            'Wisper',
            'Xtracycle',
            'Yamaha',
            'Yeti',
            'YT Industries',
            'Yuba',
            'Zerode',
        ];

        DB::table('brands')->insert(
            array_map(fn ($brand) => ['name' => $brand], $brands)
        );
    }
}
